// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.FB2015.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

import org.FB2015.Robot;

/**
 *
 */
public class CmdStrafe extends Command {
	
	Timer timer = new Timer();
	double timer_time = 0;
	double moving_speed = 0;

    public CmdStrafe(double time, double speed) {
    	timer_time = time;
    	moving_speed = speed;
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	timer.reset();
    	timer.start();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	System.out.println("OH IT WORKS!!!  YES ... NO!!!");
		Robot.chassis.mechanumDrive(moving_speed, 0, 0);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    		return timer.get() > timer_time;
    }

    // Called once after isFinished returns true
    protected void end() {
		Robot.chassis.mechanumDrive(0, 0, 0);

    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.chassis.mechanumDrive(0, 0, 0);
    }
}
